#!/bin/bash -l

# we are going to set these paramenters through cmdline (but you can always hardcoded the parameters if they are going to be fixed.:


# Now let's keep track of some information just in case anything goes wrong
echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "Task index number : $SGE_TASK_ID"
echo "=========================================================="

module load python/2.7.7
module load macs/2.1.0.20150731


INFILE=`find /restricted/projectnb/chengcancer/Simon/project/T2D/ATAC-seq/NextSeq/4shift/*.bam | head -${SGE_TASK_ID} |tail -1`
echo "NOW in TASK ${SGE_TASK_ID} : PROCESSING $INFILE ..."

# call macs2 for individual file distributed by task id

macs2 callpeak -t ${INFILE}  -f BAM -g hs -nomodel --nolambda --keep-dup all --call-summits --outdir /restricted/projectnb/chengcancer/Simon/project/T2D/ATAC-seq/NextSeq/5callPeaks/  -n $(basename ${INFILE} .bam) -B -q 0.01 --bdg --shift -100 --extsize 200

