#!/bin/bash -l

module load python/2.7.7
module load macs/2.1.0.20150731

INFILE=`find ./*.bam | head -${SGE_TASK_ID} |tail -1`
echo "NOW in TASK ${SGE_TASK_ID} : PROCESSING $INFILE ..."

# call macs2 for individual file distributed by task id

macs2 callpeak -t ${INFILE}  -f BAM -g hs -nomodel --nolambda --keep-dup all --call-summits --outdir .  -n $(basename ${INFILE} .bam) -B -q 0.01 --bdg --shift -100 --extsize 200

