#!/bin/bash -l

module load java
module load picard/2.8.0


INFILE=`find  ./*.sam  | sed 's/.sam//'| head -${SGE_TASK_ID} |tail -1`
echo "NOW in TASK ${SGE_TASK_ID} : PROCESSING $INFILE ..."

java  -jar picard.jar SortSam INPUT=${INFILE}.sam  OUTPUT=${INFILE}.sorted.bam  SORT_ORDER=coordinate TMP_DIR=`pwd`/tmp

java  -jar picard.jar MarkDuplicates  INPUT=${INFILE}.sorted.bam OUTPUT=${INFILE}.sorted.dedup.bam  METRICS_FILE=$(basename "$filename" .sam).txt REMOVE_DUPLICATES=TRUE



